#!/bin/bash

# To push you must have write access to https://github.com/matter-js/matter.js-chip.
#
# Use "docker login" command with a "personal access token (classic)" with package:write scope.
#
# Create access token here: https://github.com/settings/tokens/new?scopes=write:packages
#
# See also https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic

docker push ghcr.io/matter-js/chip:latest
