pull_request_rules:
  - name: Automatic merge on PullApprove
    conditions:
      - or:
        - "check-success=pullapprove"
        - label="fast track"
      - or:
        - "check-success=pullapprove"
        - label="hotfix"
      - "#approved-reviews-by>=1"
      - "#review-threads-unresolved=0"
      - "-draft"
      - "#check-failure=0"               # Don't auto merge with a failure
      - "#check-pending=0"               # Don't auto merge with anything pending
      - or:
        - "check-success=pullapprove"
        - "check-skipped=pullapprove"
        - "check-neutral=pullapprove"
      - label!="automated pr"             # Don't auto merge automated PRs, other processes do this
      - or:
        - "author=dependabot[bot]"        # merge dependabot PRs automatically
        - "label=automerge"               # merge PRs with the automerge label
    actions:
      merge:
        method: squash
