#!/usr/bin/env bash

# @license
# Copyright 2022-2025 Matter.js Authors
# SPDX-License-Identifier: Apache-2.0

# Run Avahi in a loop.  This allows us to exec a kill command to clear the DNS cache

while true; do
    avahi-daemon
done
